import { RegionData } from '../types'

export const regionData: RegionData[] = [
  { ags: '10041', name: 'Regionalverband Saarbrücken' },
  { ags: '10042', name: 'Merzig-Wadern' },
  { ags: '10043', name: 'Neunkirchen' },
  { ags: '10044', name: 'Saarlouis' },
  { ags: '10045', name: 'Saarpfalz-Kreis' },
  { ags: '10046', name: 'St. Wendel' },
  { ags: '11001', name: 'Berlin Mitte' },
  { ags: '11002', name: 'Berlin Friedrichshain-Kreuzberg' },
  { ags: '11003', name: 'Berlin Pankow' },
  { ags: '11004', name: 'Berlin Charlottenburg-Wilmersdorf' },
  { ags: '11005', name: 'Berlin Spandau' },
  { ags: '11006', name: 'Berlin Steglitz-Zehlendorf' },
  { ags: '11007', name: 'Berlin Tempelhof-Schöneberg' },
  { ags: '11008', name: 'Berlin Neukölln' },
  { ags: '11009', name: 'Berlin Treptow-Köpenick' },
  { ags: '11010', name: 'Berlin Marzahn-Hellersdorf' },
  { ags: '11011', name: 'Berlin Lichtenberg' },
  { ags: '11012', name: 'Berlin Reinickendorf' },
  { ags: '12051', name: 'Brandenburg an der Havel' },
  { ags: '12052', name: 'Cottbus' },
  { ags: '12053', name: 'Frankfurt (Oder)' },
  { ags: '12054', name: 'Potsdam' },
  { ags: '12060', name: 'Barnim' },
  { ags: '12061', name: 'Dahme-Spreewald' },
  { ags: '12062', name: 'Elbe-Elster' },
  { ags: '12063', name: 'Havelland' },
  { ags: '12064', name: 'Märkisch-Oderland' },
  { ags: '12065', name: 'Oberhavel' },
  { ags: '12066', name: 'Oberspreewald-Lausitz' },
  { ags: '12067', name: 'Oder-Spree' },
  { ags: '12068', name: 'Ostprignitz-Ruppin' },
  { ags: '12069', name: 'Potsdam-Mittelmark' },
  { ags: '12070', name: 'Prignitz' },
  { ags: '12071', name: 'Spree-Neiße' },
  { ags: '12072', name: 'Teltow-Fläming' },
  { ags: '12073', name: 'Uckermark' },
  { ags: '13003', name: 'Rostock (SK Rostock)' },
  { ags: '13004', name: 'Schwerin' },
  { ags: '13071', name: 'Mecklenburgische Seenplatte' },
  { ags: '13072', name: 'Rostock (LK Rostock)' },
  { ags: '13073', name: 'Vorpommern-Rügen' },
  { ags: '13074', name: 'Nordwestmecklenburg' },
  { ags: '13075', name: 'Vorpommern-Greifswald' },
  { ags: '13076', name: 'Ludwigslust-Parchim' },
  { ags: '', name: '' },
  { ags: '', name: '' },
  { ags: '', name: '' },
  { ags: '', name: '' },
]
